import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import os
path = os.getcwd()
filenames = [file for file in os.listdir(path) if 'combined_data' in file]
# df = pd.concat([pd.read_excel(path + '\\' + file) for file in filenames])
# print(df)
# df.to_pickle('emissions_data')
# df = pd.read_excel('emissions_data.xlsx')
# format = '%Y-%m-%d %H:%M:%S'
# df['Datetime'] = pd.to_datetime(df['point_time'], format=format)
# df = df.set_index(pd.DatetimeIndex(df['Datetime']))
# df.to_pickle('emissions_data')
df = pd.read_pickle('emissions_data')
df = df.drop(['point_time', 'version_moer', 'freq', 'ba_moer', 'ba_forecast', 'version_forecast'], axis=1)
# print(df)
df = df.sort_index(ascending=True)

# seperate into hours of the days
emissions_1 = df.between_time('00:00', '01:00')
print('emissions_1')
print(emissions_1)
emissions_2 = df.between_time('01:00', '02:00')
print('emissions_2')
print(emissions_2)
emissions_3 = df.between_time('02:00', '03:00')
print('emissions_3')
print(emissions_3)
emissions_4 = df.between_time('03:00', '04:00')
print('emissions_4')
print(emissions_4)
emissions_5 = df.between_time('04:00', '05:00')
print('emissions_5')
print(emissions_5)
emissions_6 = df.between_time('05:00', '06:00')
print('emissions_6')
print(emissions_6)
emissions_7 = df.between_time('06:00', '07:00')
print('emissions_7')
print(emissions_7)
emissions_8 = df.between_time('07:00', '08:00')
print('emissions_8')
print(emissions_8)
emissions_9 = df.between_time('08:00', '09:00')
print('emissions_9')
print(emissions_9)
emissions_10 = df.between_time('09:00', '10:00')
print('emissions_10')
print(emissions_10)
emissions_11 = df.between_time('10:00', '11:00')
print('emissions_11')
print(emissions_11)
emissions_12 = df.between_time('11:00', '12:00')
print('emissions_12')
print(emissions_12)
emissions_13 = df.between_time('12:00', '13:00')
print('emissions_13')
print(emissions_13)
emissions_14 = df.between_time('13:00', '14:00')
print('emissions_14')
print(emissions_14)
emissions_15 = df.between_time('14:00', '15:00')
print('emissions_15')
print(emissions_15)
emissions_16 = df.between_time('15:00', '16:00')
print('emissions_16')
print(emissions_16)
emissions_17 = df.between_time('16:00', '17:00')
print('emissions_17')
print(emissions_17)
emissions_18 = df.between_time('17:00', '18:00')
print('emissions_18')
print(emissions_18)
emissions_19 = df.between_time('18:00', '19:00')
print('emissions_19')
print(emissions_19)
emissions_20 = df.between_time('19:00', '20:00')
print('emissions_20')
print(emissions_20)
emissions_21 = df.between_time('20:00', '21:00')
print('emissions_21')
print(emissions_21)
emissions_22 = df.between_time('21:00', '22:00')
print('emissions_22')
print(emissions_22)
emissions_23 = df.between_time('22:00', '23:00')
print('emissions_23')
print(emissions_23)
emissions_24 = df.between_time('23:00', '00:00')
print('emissions_24')
print(emissions_24)

# Using Seasons
emissions_winter = df[((df['Datetime'].dt.month == 12) | (df['Datetime'].dt.month <= 2))]
# emissions_winter = emissions_winter.append(df[df['Datetime'].dt.month <= 2])
# emissions_winter = emissions_winter.sort_index(ascending=True)
print('emissions_winter')
print(emissions_winter)
emissions_spring = df[((df['Datetime'].dt.month >= 3) & (df['Datetime'].dt.month <= 5))]
print('emissions_spring')
print(emissions_spring)

emissions_summer = df[((df['Datetime'].dt.month >= 6) & (df['Datetime'].dt.month <= 8))]
print('emissions_summer')
print(emissions_summer)

emissions_fall = df[((df['Datetime'].dt.month >= 9) & (df['Datetime'].dt.month <= 11))]
print('emissions_fall')
print(emissions_fall)